// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45Ke6VLnIU_YcM2W2TGpGs-NFjtgPJM4',
    appId: '1:1051768449498:web:b4b2bb00588dbb073938e3',
    messagingSenderId: '1051768449498',
    projectId: 'cli-project-4211f',
    authDomain: 'cli-project-4211f.firebaseapp.com',
    storageBucket: 'cli-project-4211f.appspot.com',
    measurementId: 'G-4ZNNRYPJSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVL3f6-FmM56PppzGTP3e0kAWFGiXkAxg',
    appId: '1:1051768449498:android:6be3523a9e09b2973938e3',
    messagingSenderId: '1051768449498',
    projectId: 'cli-project-4211f',
    storageBucket: 'cli-project-4211f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRFAvtgDdosDmq3KgJfybNVZUr5Uaf-o',
    appId: '1:1051768449498:ios:c34a61ead46e1e433938e3',
    messagingSenderId: '1051768449498',
    projectId: 'cli-project-4211f',
    storageBucket: 'cli-project-4211f.appspot.com',
    iosBundleId: 'com.intellect.notificationPart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfRFAvtgDdosDmq3KgJfybNVZUr5Uaf-o',
    appId: '1:1051768449498:ios:a159b69e10d4cba93938e3',
    messagingSenderId: '1051768449498',
    projectId: 'cli-project-4211f',
    storageBucket: 'cli-project-4211f.appspot.com',
    iosBundleId: 'com.intellect.notificationPart.RunnerTests',
  );
}
